CONFIG_STDOUT_CONSOLE=y

CONFIG_DISPLAY=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# LIBRARIES
CONFIG_SERIAL=y
CONFIG_LIBTSM=y
CONFIG_FONTS=y
CONFIG_WCWIDTH=y
CONFIG_KEYMAP=y
CONFIG_LIBUTF8=y
CONFIG_MINITELNET=y
CONFIG_WINDOW=y
CONFIG_LUA=y
CONFIG_SYSFS=y
CONFIG_FILE_SYSTEM=y

CONFIG_DEBUG=y
CONFIG_INPUT=y
CONFIG_LIBTSM_LOG_LEVEL_DBG=y

CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_TCP=y
CONFIG_NET_IPV4=y

CONFIG_NET_DHCPV4=y

CONFIG_EVENTS=y

CONFIG_PICOLIBC=y

#CONFIG_POSIX_SYSTEM_INTERFACES=y
#CONFIG_POSIX_FILE_SYSTEM=y
#CONFIG_POSIX_DEVICE_IO=y
#CONFIG_POSIX_FD_MGMT=y
#CONFIG_POSIX_MULTI_PROCESS=y
